version: '3.6'

networks:
  arkeo:
    driver: bridge
    attachable: true

services:
  postgres:
    image: postgres:15.1-alpine
    container_name: arkeo-airdrop-pg
    restart: always
    environment:
      POSTGRES_DB: arkeo_airdrop
      POSTGRES_USER: arkeo
      POSTGRES_PASSWORD: arkeo123
    networks:
      - arkeo
    ports:
      - 5432:5432

  datagen:
    build:
      dockerfile: docker/dev/Dockerfile.indexer
    env_file:
      - docker/dev/docker.env
    depends_on:
      - postgres
    networks:
      - arkeo