apiVersion: v1
kind: Pod
metadata:
  name: admin
  namespace: foundation
spec:
  containers:
    - name: admin
      image: ghcr.io/arkeonetwork/airdroputils:latest
      imagePullPolicy: Always
      volumeMounts:
        - name: data
          mountPath: /root/data
      command:
        - /bin/bash
        - -c
        - "trap : TERM INT; sleep infinity & wait"
      resources:
        limits:
          memory: "256Mi"
          cpu: "333m"
        requests:
          memory: "128Mi"
          cpu: "66m"
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: airdroputils-data-pvc
